{{- if .Values.configMap }}
{{- if .Values.configMap.enabled }}
{{- range .Values.configMap.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "application.labels.stakater" $ | indent 4 }}
{{ include "application.labels.chart" $ | indent 4 }}
{{- if $.Values.configMap.additionalLabels }}
{{ toYaml $.Values.configMap.additionalLabels | indent 4 }}
{{- end }}
{{- if $.Values.configMap.annotations }}
  annotations:
{{ toYaml $.Values.configMap.annotations | indent 4 }}
{{- end }}
  {{- if eq .nameSuffix ""  }}
  name: {{ template "application.name" $ }}
  {{- else }}
  name: {{ template "application.name" $ }}-{{ .nameSuffix }}
  {{- end }}
{{- if $.Values.namespace.enabled }}
  namespace: {{ $.Values.namespace.name }}
{{- end }}
data:
{{ toYaml .data | indent 2 }}
---
{{- end }}
{{- end }}
{{- end }}