{{- if (.Values.ingress).enabled -}}
{{- $servicePort := .Values.ingress.servicePort -}}
{{- $pathType := .Values.ingress.pathType -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "application.name" . }}
  namespace: {{ include "application.namespace" . }}
  labels:
{{ include "application.labels" . | indent 4 }}
{{- if .Values.ingress.additionalLabels }}
{{ toYaml .Values.ingress.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end}}
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ include "application.tplvalues.render" (dict "value" $host "context" $)  }}
      http:
        paths:
          - path: /
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ template "application.name" $ }}
                port:
                  name: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ include "application.tplvalues.render" (dict "value" .Values.ingress.tls "context" $) | indent 3 }}
  {{- end -}}
{{- end -}}