{{- if .Values.ingress -}}
{{- if .Values.ingress.enabled -}}
{{- $servicePort := .Values.ingress.servicePort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "application.name" . }}
  namespace: {{ template "application.namespace" . }}
  labels:
{{ include "application.labels.stakater" . | indent 4 }}
{{ include "application.labels.chart" . | indent 4 }}
{{- if .Values.ingress.additionalLabels }}
{{ toYaml .Values.ingress.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ include "application.tplvalues.render" (dict "value" $host "context" $)  }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "application.name" $ }}
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
