{{- if .Values.prometheusRule -}}
{{- if .Values.prometheusRule.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
{{ include "application.labels.stakater" . | indent 4 }}
{{ include "application.labels.chart" . | indent 4 }}
{{- if .Values.prometheusRule.additionalLabels -}}
{{ toYaml .Values.prometheusRule.additionalLabels | indent 4 }}
{{- end }}
  name: {{ template "application.name" . }}
  namespace: {{ template "application.namespace" . }}
spec:
  groups:
{{ toYaml .Values.prometheusRule.groups | indent 4 }}
{{- end -}}
{{- end -}}